### ISSUE TITLE
Maven Central package

### ISSUE THREAD

**Issue by bilalaslam** [bascan/aws-dropwizard#1]
It would be great if you could create a Maven Central package for this. Thanks for working on this!

**Comment by bascan** [comment]
Hi Bilal,

Thanks for your interest in the project!
I'm currently finalizing the first release of SQS-Dropwizard and I expect to deliver the artifact to Maven Central next week.

I'll add another comment when it's done.
Hang on!!

Cheers, Bas

**Comment by bascan** [comment]
Hi Bilal,

I pushed all commits for our 1.0 release yesterday.
The code is being tested now. I'll release to Maven Central on Monday when no major issues have been reported.

Kind regards,
Bas

**Comment by bascan** [comment]
Hi Bilal,

I released sqs-dropwizard v1.0 to the Sonatype OSS repository: https://oss.sonatype.org/#nexus-search;quick~sqs-dropwizard.

It will be mirrored to Maven Central soon.

Have fun!
Bas
