### ISSUE TITLE
Be more flexible when handling exceptions

### ISSUE THREAD

**Issue by danielfc** [bascan/aws-dropwizard#11]
The current implementation deletes an SQS message even though an exception has been thrown:
 [SqsListenerImpl.java](https://github.com/bascan/sqs-dropwizard/blob/master/src/main/java/io/interact/sqsdw/SqsListenerImpl.java#L92-L99). In my point of view, `sqs-dropwizard` could easily be improved by adding either a `continue` to that `catch` block or provide a way of overriding a possible `deleteMessage` method or something like that.

I'll try to come up with a PR to address this issue.

**Comment by bascan** [comment]
@danielfc Thanks for submitting your issue! I'm looking forward to review your PR.
