### ISSUE TITLE
aws-java-sdk-sqs version issue

### ISSUE THREAD

**Issue by davidsantiago** [bascan/aws-dropwizard#14]
It seems that the current code depends on version 1.9.10 of aws-java-sdk-sqs, which is a fairly old version now. We want to use newer versions of AWS in our project (1.11 series), but when we build with that version of aws-java-sdk-sqs, there is a binary incompatibility that results in NoSuchMethodExceptions at runtime. 

We took your current code and built it with an updated version of aws-java-sdk-sqs. It built without changes, and fixes the incompatibility. Is there any reason the dependency version can't be bumped and the next version of the jar built with a newer version of the sqs library?

**Comment by davidsantiago** [comment]
For reference, this is the same issue: https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/22

**Comment by bascan** [comment]
Hi David,

Thanks for getting in touch! There's no particular reason why the AWS
dependency could not be updated. I'll have a look tonight and will
follow-up on it afterwards.

Cheers,
Bas

**Comment by bascan** [comment]
@davidsantiago I updated the AWS dependencies. Could you please pull master and confirm that everything works for you? If so, I'll make a new release to Maven Central.
