### ISSUE TITLE
Please update to dropwizard version 0.9.2.

### ISSUE THREAD

**Issue by V0L0DYMYR** [bascan/aws-dropwizard#3]
Please update to dropwizard version 0.9.2.

**Comment by bascan** [comment]
Dependency updated in master. Will make a new Maven release next week.

**Comment by bascan** [comment]
Maven artifact released:

``` xml
<dependency>
  <groupId>io.interact</groupId>
  <artifactId>sqs-dropwizard</artifactId>
  <version>1.0.2</version>
</dependency>
```

Please allow some time for Maven Central to sync up.

**Comment by V0L0DYMYR** [comment]
Many thanks!
