### ISSUE TITLE
Add default provider chain capability for credentials

### ISSUE THREAD

**Issue by danielfc** [bascan/aws-dropwizard#4]
Currently, we are forced to pass a value for both key and secret from our `config.yml` file. Would it be possible to check if both are empty and if yes, use the `DefaultAWSCredentialsProviderChain`? That way we could leverage authentication to our instance roles.

The change would be very simple. The code [here](https://github.com/bascan/sqs-dropwizard/blob/master/src/main/java/io/interact/sqsdw/SqsFactory.java#L50-L63) would be replaced by:

``` java
final AmazonSQS sqs = new AmazonSQSClient(new DefaultAWSCredentialsProviderChain());
```

If credentials are empty from `config.yml`. I'll try to open a PR with this soon.

Reference: [Providing AWS Credentials in the AWS SDK for Java](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html).

**Comment by bascan** [comment]
@danielfc Thanks for your PR, I'll release a new Maven artifact including your commit next week.
