### ISSUE TITLE
aws-sdk dependency

### ISSUE THREAD

**Issue by stve** [bascan/aws-dropwizard#7]
Instead of having a dependency on `aws-java-sdk`, would it be possible to just depend on `aws-java-sdk-sqs`? 

It appears that each AWS SDK has it's own [dependencies](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/pom.xml#L17-L36) so theoretically it should be possible.

**Comment by bascan** [comment]
Many thanks for reporting your suggestion!
I'll try to find some time this week to change the AWS dependency.

**Comment by bascan** [comment]
@stve your PR is part of the v1.0.4 release which is now available from Maven Central. Thanks again for your support!
